/* ATPL Mam Sheet -> Compliance Salary V2. Event-driven only; no polling/observer. */
(function(){'use strict';
if(window.__MAM_SALARY_V2__)return;window.__MAM_SALARY_V2__=1;
var S={rows:[],days:31,ref:null,seq:0};
var G10=new Set(['26449','26493','26653','26654','26655','26656','26657','26658','26659','26660','26661','26662','26663','26664','26665','26666','26668','26669','26670','26671','26672','26674','26675','26676']);
var PCAP=new Set(['135','387','419','10586','25391','25429']);
function $(x){return document.getElementById(x)}
function E(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function N(v){if(typeof v==='number')return isFinite(v)?v:NaN;v=String(v==null?'':v).replace(/[,₹]/g,'').trim();return !v||/^#/.test(v)?NaN:+v}
function R(v){return Math.round((+v||0)+Number.EPSILON)}
function R2(v){return Math.round(((+v||0)+Number.EPSILON)*100)/100}
function CK(v){v=String(v==null?'':v).toUpperCase().replace(/[^A-Z0-9]/g,'');return /^\d+$/.test(v)?v.replace(/^0+(?=\d)/,''):v}
function NK(v){return String(v==null?'':v).toUpperCase().replace(/[^A-Z0-9]/g,'')}
function H(v){return String(v==null?'':v).toLowerCase().replace(/[\n\r]+/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function V(v){v=String(v==null?'':v).trim().toUpperCase();return !!v&&!['NA','N/A','#N/A','0','-','NONE'].includes(v)}
function C(v,a,b){return Math.max(a,Math.min(b,v))}
function med(a){if(!a.length)return NaN;a=a.slice().sort(function(x,y){return x-y});var m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function user(){try{var s=JSON.parse(sessionStorage.getItem('ATPL_UserSession_V5')||'null'),a=JSON.parse(localStorage.getItem('ATPL_UserAccess_V1')||'[]');return s&&Array.isArray(a)?a.find(function(u){return String(u.id).toLowerCase()===String(s.id).toLowerCase()})||null:null}catch(_){return null}}
function ok(){var u=user();return !u||u.admin===true||(u.access||[]).indexOf('mamsalary')>=0}
function master(){try{if(window.EM&&Array.isArray(EM.data))return EM.data;if(Array.isArray(window.EMP_MASTER_DATA))return window.EMP_MASTER_DATA;var a=JSON.parse(localStorage.getItem('AroraTextilesEmployeeMasterV3')||'[]');if(Array.isArray(a))return a;if(a&&Array.isArray(a.data))return a.data}catch(_){ }return[]}
function maps(){var bc={},bn={};master().forEach(function(e){var c=CK(e.emp_id),n=NK(e.name);if(c&&!bc[c])bc[c]=e;if(n)(bn[n]||(bn[n]=[])).push(e)});return{c:bc,n:bn}}
function monthDaysFromTitle(rows,hi){var t=[];for(var i=0;i<Math.min(hi,5);i++)t=t.concat(rows[i]||[]);var s=t.join(' ').toLowerCase(),mm={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};for(var k in mm){if(s.indexOf(k)>=0){var y=(s.match(/(?:20)?(\d{2})/)||[])[1];y=y?2000+(+y):new Date().getFullYear();return new Date(y,mm[k]+1,0).getDate()}}return NaN}
function findHeader(rows){for(var i=0;i<Math.min(rows.length,15);i++){var hs=(rows[i]||[]).map(H),hasId=hs.some(function(x){return x==='employee id'||x==='emp code'||x==='employee code'}),hasName=hs.some(function(x){return x.indexOf('name of employee')>=0||x==='employee name'||x==='name'}),hasGross=hs.some(function(x){return x.indexOf('gross')>=0});if(hasId&&hasName&&hasGross)return i}return -1}
function col(hs,test){for(var i=0;i<hs.length;i++)if(test(hs[i],i))return i;return -1}
function refRead(wb){var sn=wb.SheetNames.indexOf('Main Sheet')>=0?'Main Sheet':wb.SheetNames[0],rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,raw:true,defval:''}),hi=findHeader(rows);if(hi<0)throw new Error('Last Salary Sheet me Main salary header nahi mila.');var hs=(rows[hi]||[]).map(H);
var ix={id:col(hs,function(x){return x==='employee id'||x==='emp code'||x==='employee code'}),name:col(hs,function(x){return x.indexOf('name of employee')>=0||x==='employee name'||x==='name'}),basic:col(hs,function(x){return x==='basic'}),gross:col(hs,function(x){return x==='gross total salary'||x==='gross salary'||x==='gross'}),days:col(hs,function(x){return x==='month of days'||x==='month days'}),paid:col(hs,function(x){return x==='paid days'}),ot:col(hs,function(x){return x==='over time hours'||x==='overtime hours'||x==='ot'}),total:col(hs,function(x){return x==='total gross salary'}),pf:col(hs,function(x){return x.indexOf('pf 12')>=0}),esi:col(hs,function(x){return x.indexOf('esic 0 75')>=0||x.indexOf('esi 0 75')>=0}),bonus:col(hs,function(x){return x.indexOf('earned bonus')>=0}),egross:col(hs,function(x){return x==='gross earned salary'}),eot:col(hs,function(x){return x.indexOf('earned overtime')>=0||x.indexOf('earned over time')>=0})};
if(ix.basic<0||ix.gross<0||ix.paid<0||ix.total<0)throw new Error('Last Salary Sheet me Basic/Gross/Paid Days/Total Gross columns required hain.');
var data=[];for(var r=hi+1;r<rows.length;r++){var a=rows[r]||[],id=String(a[ix.id]||'').trim(),name=String(a[ix.name]||'').trim(),b=N(a[ix.basic]),g=N(a[ix.gross]),pd=N(a[ix.paid]),ot=ix.ot>=0?N(a[ix.ot]):0,t=N(a[ix.total]);if(!name||!isFinite(b)||!isFinite(g)||!isFinite(pd)||!isFinite(t))continue;data.push({id:id,name:name,b:b,g:g,pd:pd,ot:isFinite(ot)?ot:0,total:t,pf:ix.pf>=0?N(a[ix.pf]):NaN,esi:ix.esi>=0?N(a[ix.esi]):NaN,bonus:ix.bonus>=0?N(a[ix.bonus]):NaN,egross:ix.egross>=0?N(a[ix.egross]):NaN,eot:ix.eot>=0?N(a[ix.eot]):NaN})}
if(!data.length)throw new Error('Last Salary Sheet me employee rows read nahi hui.');var ds=[];if(ix.days>=0)for(var q=hi+1;q<rows.length;q++){var dd=N((rows[q]||[])[ix.days]);if(isFinite(dd)&&dd>=28&&dd<=31)ds.push(dd)}var refDays=R(med(ds));if(!(refDays>=28&&refDays<=31))refDays=monthDaysFromTitle(rows,hi);if(!(refDays>=28&&refDays<=31))refDays=S.days;
var divs=[];if(ix.eot>=0)data.forEach(function(x){if(x.g>0&&x.ot>0&&isFinite(x.eot)&&x.eot>0){var d=x.g*x.ot/(4*x.eot);if(d>=20&&d<=35)divs.push(d)}});var otDiv=divs.length?R(med(divs)):0;if(!otDiv){var cand=[26,refDays,30,31].filter(function(x,i,a){return a.indexOf(x)===i}),best=null;cand.forEach(function(dv){var sc=0,n=0;data.forEach(function(x){if(!x.g||!x.pd||!isFinite(x.total))return;var eg=x.g*x.pd/refDays,eb=x.b*x.pd/refDays,oa=x.g/dv/8*2*x.ot,cc=[eg+oa,eg+eb*.0833+oa,eg+eg*.10+oa],de=Math.min.apply(null,cc.map(function(v){return Math.abs(R(v)-x.total)}));sc+=Math.min(de,1000);n++});sc=n?sc/n:9999;if(!best||sc<best.sc)best={d:dv,sc:sc}});otDiv=best?best.d:26}
var bases=['basic','gross','total'],bb=null;bases.forEach(function(bs){var sc=0,n=0;data.forEach(function(x){if(!isFinite(x.esi)||x.esi<=0)return;var eb=x.b*x.pd/refDays,eg=x.g*x.pd/refDays,v=bs==='basic'?eb:(bs==='gross'?eg:x.total);sc+=Math.abs(R(v*.0075)-x.esi);n++});sc=n?sc/n:9999;if(!bb||sc<bb.sc)bb={b:bs,sc:sc}});var esiBase=bb?bb.b:'basic',byCode={},byName={},count={none:0,b833:0,g10:0,pf:0,esi:0};
data.forEach(function(x){var eb=x.b*x.pd/refDays,eg=x.g*x.pd/refDays,oa=x.g/otDiv/8*2*x.ot,br='none';if(isFinite(x.bonus)){if(x.bonus>0){var db=Math.abs(R(eb*.0833)-x.bonus),dg=Math.abs(R(eg*.10)-x.bonus);br=db<=dg?'b833':'g10'}}else{var cc={none:Math.abs(R(eg+oa)-x.total),b833:Math.abs(R(eg+eb*.0833+oa)-x.total),g10:Math.abs(R(eg+eg*.10+oa)-x.total)};br=Object.keys(cc).sort(function(a,b){return cc[a]-cc[b]})[0]}count[br]++;
var pfm='none';if(isFinite(x.pf)&&x.pf>0){var pfa=R(eb*.12);pfm=(pfa>1800&&Math.abs(x.pf-1800)<=2)?'cap':'actual';count.pf++}var esm=(isFinite(x.esi)&&x.esi>0)?esiBase:'none';if(esm!=='none')count.esi++;var rule={bonus:br,pf:pfm,esi:esm};var c=CK(x.id),n=NK(x.name);if(c)byCode[c]=rule;if(n&&!byName[n])byName[n]=rule});return{source:sn,rows:data.length,monthDays:refDays,otDiv:otDiv,esiBase:esiBase,byCode:byCode,byName:byName,count:count}}
function fallback(r){var e=r.emp||{},id=CK(e.emp_id||r.code),b=+e.basic||0;return{bonus:G10.has(id)?'g10':(b<=21000?'b833':'none'),pf:V(e.pf_no)?(PCAP.has(id)?'cap':'actual'):'none',esi:V(e.esi_no)?'basic':'none'}}
function learned(r){if(S.ref){var c=CK(r.code),n=NK(r.name),x=(c&&S.ref.byCode[c])||S.ref.byName[n];if(x)return x}return fallback(r)}
function modes(r){var a=learned(r);return{bonus:r.rule&&r.rule!=='auto'?r.rule:a.bonus,pf:r.pfm&&r.pfm!=='auto'?r.pfm:a.pf,esi:r.es&&r.es!=='auto'?r.es:a.esi}}
function core(r,d,o){var e=r.emp||{},b=+e.basic||0,g=+e.gross||0,eb=b*d/S.days,eg=g*d/S.days,m=modes(r),x=0;if(m.bonus==='b833')x=eb*.0833;if(m.bonus==='g10')x=eg*.10;return{eb:eb,eg:eg,bonus:x,ot:g/(S.ref&&S.ref.otDiv?S.ref.otDiv:26)/8*2*o,t:R(eg+x+(g?g/(S.ref&&S.ref.otDiv?S.ref.otDiv:26)/8*2*o:0))}}
function calc(r){var c=core(r,r.d,r.o),m=modes(r),pf=0;if(m.pf==='cap')pf=Math.min(1800,R(c.eb*.12));else if(m.pf==='actual')pf=R(c.eb*.12);var esi=0;if(m.esi==='basic')esi=R(c.eb*.0075);else if(m.esi==='gross')esi=R(c.eg*.0075);else if(m.esi==='total')esi=R(c.t*.0075);var man=isFinite(r.man)?R2(r.man):0,gap=isFinite(r.man)?R2(man-c.t):0;r.tg=c.t;r.bonus=R(c.bonus);r.otamt=R(c.ot);r.pf=pf;r.esi=esi;r.diff=gap>0?gap:0;r.autoAdv=gap<0?-gap:0;r.adv=R2((+r.advExtra||0)+r.autoAdv);r.ded=R2(r.diff+pf+esi+r.adv);r.net=R2(r.tg-r.ded);r.mr=man}
function suggest(r){var e=r.emp||{},g=+e.gross||0,t=isFinite(r.man)?+r.man:0;if(!r.emp||!isFinite(r.man)||!g){r.d=0;r.o=0;r.delta=9999;calc(r);return}var est=C(t/(g/S.days||1),0,S.days),lo=C(Math.floor((est-5)*2)/2,0,S.days),hi=C(Math.ceil((est+5)*2)/2,0,S.days),best=null;for(var d=lo;d<=hi+.001;d+=.5)for(var o=0;o<=32;o+=.5){var z=core(r,d,o),de=Math.abs(t-z.t),sc=de*100+(z.t>t?10:0)+o*.25+Math.abs(d-est)*.15;if(!best||sc<best.sc)best={d:R2(d),o:R2(o),de:de,sc:sc}}r.d=best?best.d:0;r.o=best?best.o:0;r.delta=best?best.de:9999;calc(r)}
function parseMam(wb){var M=maps(),out=[],seen={},seq=0;wb.SheetNames.forEach(function(sn){var cat='';XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,raw:true,defval:''}).forEach(function(a,i){var A=String(a[0]||'').trim(),B=String(a[1]||'').trim(),CC=String(a[2]||'').trim(),al=H(A),bl=H(B),cl=H(CC);if(['code','emp code','employee code'].includes(al)){if(B&&!(bl.indexOf('employee')>=0&&bl.indexOf('name')>=0))cat=B.trim();return}if((bl.indexOf('employee')>=0&&bl.indexOf('name')>=0)||cl==='amount'||cl.indexOf('manual amount')>=0)return;var man=N(a[2]);if(!B||!isFinite(man))return;var ck=CK(A),nk=NK(B),e=ck?M.c[ck]:null,mm='code';if(!e&&M.n[nk]&&M.n[nk].length===1){e=M.n[nk][0];mm='name'}var key=ck?'C'+ck:'N'+nk+'|'+H(cat||sn);if(seen[key])return;seen[key]=1;var r={code:A,name:B,codeMissing:!ck,man:man,raw:CC,emp:e||null,match:e?mm:'none',cat:cat||(!/^sheet\d*$/i.test(sn)?sn:''),src:sn,row:i+1,seq:seq++,d:0,o:0,advExtra:0,rule:'auto',pfm:'auto',es:'auto'};suggest(r);out.push(r)})});out.sort(function(a,b){return (a.codeMissing===b.codeMissing)?a.seq-b.seq:(a.codeMissing?1:-1)});return out}
function outCode(r){return r.codeMissing?'':((r.emp&&r.emp.emp_id)||r.code||'')}
function status(r){if(r.codeMissing)return'<b class="bad">CODE MISSING · BOTTOM</b>';if(!r.emp)return'<b class="bad">MASTER MATCH NAHI</b>';var lr=S.ref&&((CK(r.code)&&S.ref.byCode[CK(r.code)])||S.ref.byName[NK(r.name)]);if(S.ref&&!lr)return'<b class="warn">NEW EMP · RULE CHECK</b>';if(!isFinite(r.man))return'<b class="bad">AMOUNT CHECK</b>';return r.delta<=200?'<b class="good">READY</b>':'<b class="warn">WORKING/OT CHECK</b>'}
function render(){var box=$('msbody');if(!box)return;var m=S.rows.filter(function(r){return r.emp}).length,blank=S.rows.filter(function(r){return r.codeMissing}).length,rd=S.rows.filter(function(r){return r.emp&&r.delta<=200}).length;$('msstats').innerHTML='<span><b>'+S.rows.length+'</b> Mam Rows</span><span><b>'+m+'</b> Master Matched</span><span><b>'+rd+'</b> Auto Ready</span><span><b>'+blank+'</b> Without Code · Bottom</span>';if(!S.rows.length){box.innerHTML='<div class="msempty">Mam ki Salary Sheet upload karo.</div>';return}var h='<div class="mswrap"><table><thead><tr><th>#</th><th>Code</th><th>Name</th><th>Mam Category</th><th>Manual</th><th>Paid Days</th><th>OT</th><th>Bonus Rule</th><th>PF Rule</th><th>ESIC Rule</th><th>Total Gross</th><th>Bonus</th><th>PF</th><th>ESIC</th><th>Advance</th><th>Diff</th><th>Total Ded.</th><th>Net Paid</th><th>Status</th></tr></thead><tbody>';S.rows.forEach(function(r,i){var e=r.emp||{},mm=modes(r);h+='<tr'+((!r.emp||r.codeMissing)?' class="x"':'')+'><td>'+(i+1)+'</td><td>'+E(outCode(r))+'</td><td>'+E(e.name||r.name)+(r.match==='name'?'<small>name match</small>':'')+'</td><td><input class="cat" data-i="'+i+'" data-f="cat" value="'+E(r.cat||'')+'"></td><td><input data-i="'+i+'" data-f="man" type="number" step=".01" value="'+(isFinite(r.man)?R2(r.man):'')+'"></td><td><input data-i="'+i+'" data-f="d" type="number" step=".5" min="0" max="'+S.days+'" value="'+r.d+'"></td><td><input data-i="'+i+'" data-f="o" type="number" min="0" step=".5" value="'+r.o+'"></td><td><select data-i="'+i+'" data-f="rule"><option value="auto">Auto ('+E(mm.bonus)+')</option><option value="b833">Basic 8.33%</option><option value="g10">Gross 10%</option><option value="none">No Bonus</option></select></td><td><select data-i="'+i+'" data-f="pfm"><option value="auto">Auto ('+E(mm.pf)+')</option><option value="actual">12% Actual</option><option value="cap">Cap ₹1800</option><option value="none">No PF</option></select></td><td><select data-i="'+i+'" data-f="es"><option value="auto">Auto ('+E(mm.esi)+')</option><option value="basic">Basic 0.75%</option><option value="gross">Gross 0.75%</option><option value="total">Total 0.75%</option><option value="none">No ESIC</option></select></td><td data-v="tg">'+R(r.tg)+'</td><td data-v="bonus">'+R(r.bonus)+'</td><td data-v="pf">'+R(r.pf)+'</td><td data-v="esi">'+R(r.esi)+'</td><td><input data-i="'+i+'" data-f="advExtra" type="number" step=".01" min="0" value="'+R2(r.advExtra||0)+'"><small>'+(r.autoAdv?'Auto adj: '+R2(r.autoAdv):'')+'</small></td><td data-v="diff">'+R2(r.diff)+'</td><td data-v="ded">'+R2(r.ded)+'</td><td data-v="net"><b>'+R2(r.net)+'</b></td><td data-v="st">'+status(r)+'</td></tr>'});box.innerHTML=h+'</tbody></table></div>';S.rows.forEach(function(r,i){var tr=box.querySelectorAll('tbody tr')[i];if(tr){tr.querySelector('[data-f="rule"]').value=r.rule;tr.querySelector('[data-f="pfm"]').value=r.pfm;tr.querySelector('[data-f="es"]').value=r.es}})}
function upd(i){var r=S.rows[i],tr=$('msbody').querySelectorAll('tbody tr')[i];if(!r||!tr)return;calc(r);['tg','bonus','pf','esi','diff','ded'].forEach(function(k){var z=tr.querySelector('[data-v="'+k+'"]');if(z)z.textContent=(k==='diff'||k==='ded')?R2(r[k]):R(r[k])});tr.querySelector('[data-v="net"]').innerHTML='<b>'+R2(r.net)+'</b>';tr.querySelector('[data-v="st"]').innerHTML=status(r);var ad=tr.querySelector('[data-f="advExtra"]');if(ad){var sm=ad.parentNode.querySelector('small');if(sm)sm.textContent=r.autoAdv?'Auto adj: '+R2(r.autoAdv):''}}
function auto(){S.rows.forEach(suggest);render();note('Last Salary rules + Mam amount se Paid Days/OT auto calculate ho gaye. Yellow rows review kar lena.',0)}
function sum(a,k){return R2(a.reduce(function(x,r){return x+(+r[k]||0)},0))}
function se(a,k){return R2(a.reduce(function(x,r){return x+(+(r.emp&&r.emp[k])||0)},0))}
function remarks(r){if(r.codeMissing)return'EMP CODE MISSING';if(!r.emp)return'EMP MASTER MATCH NAHI';if(r.delta>200)return'CHECK WORKING/OT';return''}
function mainAOA(a){var z=[['S.NO.','Employee ID','Name of employee','Father Name','Date of Birth','Date of Joining','PF NO.','ESI NO.','Gender','Department','Designation','Category','Basic','Gross','PAID DAYS','OT','TOTAL GROSS SALARY','Manual Amount','DIFF.','PF','ESIC','ADVANCE DEDUCTION','TOTAL DEDUCTION','NET PAID','REMARKS']];a.forEach(function(r,i){var e=r.emp||{};z.push([i+1,outCode(r),e.name||r.name,e.father||'',e.dob||'',e.doj||'',e.pf_no||'',e.esi_no||'',e.gender||'',e.dept||'',e.desig||'',r.cat||'',+e.basic||0,+e.gross||0,r.d,r.o,r.tg,r.mr,r.diff,r.pf,r.esi,r.adv,r.ded,r.net,remarks(r)])});z.push(['','TOTAL','','','','','','','','','','',se(a,'basic'),se(a,'gross'),sum(a,'d'),sum(a,'o'),sum(a,'tg'),sum(a,'mr'),sum(a,'diff'),sum(a,'pf'),sum(a,'esi'),sum(a,'adv'),sum(a,'ded'),sum(a,'net'),'']);return z}
function subAOA(a){var z=[['S.NO.','EMPLOYEE ID','Name','Category','Basic','Gross','Paid Days','OT','Total Gross','Manual Amount','Diff.','PF','ESIC','Advance','Deduction','Net Paid']];a.forEach(function(r,i){var e=r.emp||{};z.push([i+1,outCode(r),e.name||r.name,r.cat||'',+e.basic||0,+e.gross||0,r.d,r.o,r.tg,r.mr,r.diff,r.pf,r.esi,r.adv,r.ded,r.net])});z.push(['','TOTAL','','',se(a,'basic'),se(a,'gross'),sum(a,'d'),sum(a,'o'),sum(a,'tg'),sum(a,'mr'),sum(a,'diff'),sum(a,'pf'),sum(a,'esi'),sum(a,'adv'),sum(a,'ded'),sum(a,'net')]);return z}
function formulaParts(r,row,main){var m=modes(r),d=S.days,od=S.ref&&S.ref.otDiv?S.ref.otDiv:26,b=main?'M':'E',g=main?'N':'F',pd=main?'O':'G',ot=main?'P':'H',tg=main?'Q':'I',man=main?'R':'J',df=main?'S':'K',pf=main?'T':'L',esi=main?'U':'M',adv=main?'V':'N',ded=main?'W':'O',net=main?'X':'P';var eg=g+row+'*'+pd+row+'/'+d,eb=b+row+'*'+pd+row+'/'+d,bonus=m.bonus==='b833'?'+('+eb+')*8.33%':(m.bonus==='g10'?'+('+eg+')*10%':''),tf='ROUND('+eg+bonus+'+'+g+row+'/'+od+'/8*2*'+ot+row+',0)',pff=m.pf==='cap'?'MIN(1800,ROUND('+eb+'*12%,0))':(m.pf==='actual'?'ROUND('+eb+'*12%,0)':'0'),esif=m.esi==='basic'?'ROUND('+eb+'*0.75%,0)':(m.esi==='gross'?'ROUND('+eg+'*0.75%,0)':(m.esi==='total'?'ROUND('+tg+row+'*0.75%,0)':'0')),adf='MAX('+tg+row+'-'+man+row+',0)+'+R2(r.advExtra||0);return{tg:'='+tf,diff:'=MAX('+man+row+'-'+tg+row+',0)',pf:'='+pff,esi:'='+esif,adv:'='+adf,ded:'='+df+row+'+'+pf+row+'+'+esi+row+'+'+adv+row,net:'='+tg+row+'-'+ded+row}}
function setF(ws,addr,f,v){ws[addr]={t:'n',f:f.replace(/^=/,''),v:+v||0}}
function formulasMain(ws,a){a.forEach(function(r,i){var row=i+2,f=formulaParts(r,row,true);setF(ws,'Q'+row,f.tg,r.tg);setF(ws,'S'+row,f.diff,r.diff);setF(ws,'T'+row,f.pf,r.pf);setF(ws,'U'+row,f.esi,r.esi);setF(ws,'V'+row,f.adv,r.adv);setF(ws,'W'+row,f.ded,r.ded);setF(ws,'X'+row,f.net,r.net)});var tr=a.length+2;['M','N','O','P','Q','R','S','T','U','V','W','X'].forEach(function(c){var cell=ws[c+tr]||{t:'n',v:0};cell.f='SUM('+c+'2:'+c+(tr-1)+')';ws[c+tr]=cell})}
function formulasSub(ws,a){a.forEach(function(r,i){var row=i+2,f=formulaParts(r,row,false);setF(ws,'I'+row,f.tg,r.tg);setF(ws,'K'+row,f.diff,r.diff);setF(ws,'L'+row,f.pf,r.pf);setF(ws,'M'+row,f.esi,r.esi);setF(ws,'N'+row,f.adv,r.adv);setF(ws,'O'+row,f.ded,r.ded);setF(ws,'P'+row,f.net,r.net)});var tr=a.length+2;['E','F','G','H','I','J','K','L','M','N','O','P'].forEach(function(c){var cell=ws[c+tr]||{t:'n',v:0};cell.f='SUM('+c+'2:'+c+(tr-1)+')';ws[c+tr]=cell})}
function sn(v,used){var b=String(v||'OTHER').replace(/[\\\/?*\[\]:]/g,' ').replace(/\s+/g,' ').trim().slice(0,31)||'OTHER',x=b,n=2;while(used[x]){var t=' '+n++;x=b.slice(0,31-t.length)+t}used[x]=1;return x}
function build(withFormula){S.rows.forEach(calc);var w=XLSX.utils.book_new(),u={'Main Sheet':1},ws=XLSX.utils.aoa_to_sheet(mainAOA(S.rows));ws['!cols']=[7,12,24,20,13,13,17,15,9,18,18,18,11,11,10,8,17,14,10,9,9,16,16,14,22].map(function(x){return{wch:x}});ws['!autofilter']={ref:'A1:Y'+(S.rows.length+1)};if(withFormula)formulasMain(ws,S.rows);XLSX.utils.book_append_sheet(w,ws,'Main Sheet');var g={};S.rows.forEach(function(r){var k=r.cat||'OTHER';(g[k]||(g[k]=[])).push(r)});Object.keys(g).forEach(function(k){g[k].sort(function(a,b){return (a.codeMissing===b.codeMissing)?a.seq-b.seq:(a.codeMissing?1:-1)})});Object.keys(g).sort().forEach(function(k){var s=XLSX.utils.aoa_to_sheet(subAOA(g[k]));s['!cols']=[7,12,23,18,11,11,10,8,14,14,10,9,9,11,11,13].map(function(x){return{wch:x}});s['!autofilter']={ref:'A1:P'+(g[k].length+1)};if(withFormula)formulasSub(s,g[k]);XLSX.utils.book_append_sheet(w,s,sn(k,u))});var b=[['S.NO.','Employee ID','Name','Bank Name','IFSC Code','Account Number','PF No.','ESI No.']];S.rows.forEach(function(r,i){var e=r.emp||{};b.push([i+1,outCode(r),e.name||r.name,e.bank_name||'',e.ifsc||'',e.account_no||'',e.pf_no||'',e.esi_no||''])});var bs=XLSX.utils.aoa_to_sheet(b);bs['!cols']=[7,12,23,22,16,22,18,18].map(function(x){return{wch:x}});XLSX.utils.book_append_sheet(w,bs,sn('BANK DETAILS',u));var rv=[['Source Sheet','Row','Emp Code','Employee Name','Mam Category','Manual Amount','Issue']];S.rows.forEach(function(r){var x=remarks(r);if(x)rv.push([r.src,r.row,r.code,r.name,r.cat,isFinite(r.man)?R2(r.man):r.raw,x])});if(rv.length>1)XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet(rv),sn('REVIEW',u));if(withFormula){w.Workbook=w.Workbook||{};w.Workbook.CalcPr={calcMode:'auto',fullCalcOnLoad:'1',forceFullCalc:'1'}}return w}
function dl(withFormula){if(!S.rows.length)return note('Pehle Mam ki Sheet upload karo.',1);var w=build(withFormula),base=(($('msname')&&$('msname').value)||'Salary Compliance').replace(/[^A-Za-z0-9 _-]/g,'').replace(/\s+/g,'_'),f=base+(withFormula?'_With_Formula.xlsx':'_Without_Formula.xlsx');XLSX.writeFile(w,f);note((withFormula?'Formula wali':'Final values wali')+' Compliance Excel ready hai.',0)}
function note(t,b){var x=$('msnote');if(x){x.textContent=t;x.className='msnote '+(b?'e':'')}}
async function mamFile(f){if(!f)return;note('Mam ki Sheet read ho rahi hai…',0);try{var wb=XLSX.read(await f.arrayBuffer(),{type:'array',raw:true});S.rows=parseMam(wb);render();note(S.rows.length+' rows read. Mam category preserved; blank-code employees bottom me rakhe gaye.',0)}catch(e){S.rows=[];render();note('Mam file read error: '+e.message,1)}}
async function refFile(f){if(!f)return;note('Last Salary Sheet ke PF/ESIC/Bonus/OT rules learn ho rahe hain…',0);try{var wb=XLSX.read(await f.arrayBuffer(),{type:'array',raw:true});S.ref=refRead(wb);if(S.rows.length)S.rows.forEach(suggest);render();refNote();note('Last Salary rules learned successfully. Ab calculation isi pattern se hogi.',0)}catch(e){S.ref=null;refNote();note('Reference file error: '+e.message,1)}}
function refNote(){var x=$('msrefinfo');if(!x)return;if(!S.ref){x.innerHTML='<b>No reference loaded.</b> Default rules use honge.';return}x.innerHTML='<b>✅ Last Salary Learned:</b> '+S.ref.rows+' employees · Month Days '+S.ref.monthDays+' · OT divisor <b>'+S.ref.otDiv+'</b> · ESIC base <b>'+E(S.ref.esiBase.toUpperCase())+'</b> · Bonus rules: '+S.ref.count.b833+' Basic 8.33%, '+S.ref.count.g10+' Gross 10%, '+S.ref.count.none+' No Bonus.'}
function full(){var p=$('page-mamsalary'),b=$('msfull');if(!p)return;var on=!p.classList.contains('msFull');p.classList.toggle('msFull',on);if(b)b.textContent=on?'✕ Exit Full Screen':'⛶ Full Screen'}
function style(){if($('mscss'))return;var x=document.createElement('style');x.id='mscss';x.textContent='#page-mamsalary{padding:18px;background:#f6f8fc}.msh{max-width:1700px;margin:auto}.mstop{padding:18px 20px;border-radius:15px;background:linear-gradient(135deg,#0f172a,#1d4ed8);color:white;display:flex;justify-content:space-between;gap:15px;align-items:center}.mstop h2{margin:0 0 5px}.mstop p{margin:0;color:#dbeafe;font-size:11px}.msctl{display:grid;grid-template-columns:1.2fr 1.2fr 90px 1fr auto auto auto auto;gap:9px;align-items:end;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:12px;margin:12px 0}.msctl label{display:block;font-size:9px;font-weight:800;color:#475569;margin-bottom:4px}.msctl input{width:100%;box-sizing:border-box;padding:8px;border:1px solid #cbd5e1;border-radius:7px}.msbtn{border:0;border-radius:8px;padding:9px 12px;background:#2563eb;color:#fff;font-size:10px;font-weight:800;cursor:pointer;white-space:nowrap}.msbtn.g{background:#059669}.msbtn.p{background:#7c3aed}.msbtn.z{background:#e2e8f0;color:#0f172a}#msrefinfo{background:#eff6ff;border:1px solid #bfdbfe;color:#1e3a8a;border-radius:9px;padding:9px 11px;font-size:10px;margin-bottom:8px}#msstats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:8px}#msstats span{background:#fff;border:1px solid #e2e8f0;border-radius:9px;padding:9px;font-size:9px;color:#64748b}#msstats b{font-size:17px;color:#0f172a;margin-right:6px}.msnote{padding:8px 10px;background:#ecfdf5;color:#047857;border-radius:8px;font-size:10px;margin-bottom:8px}.msnote.e{background:#fef2f2;color:#b91c1c}.mswrap{max-height:62vh;overflow:auto;background:#fff;border:1px solid #e2e8f0;border-radius:10px}.mswrap table{border-collapse:collapse;width:max-content;min-width:100%;font-size:9px}.mswrap th{position:sticky;top:0;z-index:2;background:#0f172a;color:#fff;padding:7px;white-space:nowrap}.mswrap td{padding:5px;border:1px solid #e2e8f0;white-space:nowrap}.mswrap input,.mswrap select{font-size:9px;padding:4px;border:1px solid #cbd5e1;border-radius:5px;max-width:105px}.mswrap input.cat{min-width:130px;max-width:160px}.mswrap tr.x{background:#fff1f2}.good{color:#047857}.warn{color:#b45309}.bad{color:#b91c1c}.mswrap small{display:block;color:#0284c7;font-size:8px}.msempty{padding:40px;text-align:center;color:#64748b;background:#fff;border-radius:10px}.msFull{position:fixed!important;inset:0!important;z-index:999999!important;overflow:auto!important;background:#f6f8fc!important;padding:10px!important}.msFull .msh{max-width:none!important}.msFull .mswrap{max-height:calc(100vh - 245px)!important}@media(max-width:1100px){.msctl{grid-template-columns:1fr 1fr 1fr 1fr}#msstats{grid-template-columns:1fr 1fr}}';document.head.appendChild(x)}
function inject(){style();if(!$('vn-mamsalary')){var n=document.createElement('div');n.id='vn-mamsalary';n.className='vitem';n.innerHTML='<span class="vi">🧾</span>Mam → Compliance';n.onclick=function(){if(!ok())return alert('Is feature ka access nahi diya gaya.');if(window.goPage)goPage('mamsalary')};var r=$('vn-sync');if(r&&r.parentNode)r.parentNode.insertBefore(n,r);if(!ok())n.style.display='none'}if(!$('page-mamsalary')){var p=document.createElement('div');p.id='page-mamsalary';p.className='page';p.innerHTML='<div class="msh"><div class="mstop"><div><h2>🧾 Mam Sheet → Compliance Salary</h2><p>Last Salary se rules learn → Mam category preserve → Employee Master details → PF/ESIC/Bonus/OT auto calculation → Formula/Final Excel.</p></div><button id="msfull" class="msbtn z">⛶ Full Screen</button></div><div class="msctl"><div><label>LAST SALARY SHEET (REFERENCE)</label><input id="msref" type="file" accept=".xlsx,.xls"></div><div><label>MAM KI SHEET</label><input id="msfile" type="file" accept=".xlsx,.xls"></div><div><label>MONTH DAYS</label><input id="msdays" type="number" min="28" max="31" value="31"></div><div><label>FILE NAME</label><input id="msname" value="Salary Compliance"></div><button id="msauto" class="msbtn">⚡ Auto Calculate</button><button id="msdlf" class="msbtn p">⬇ With Formula</button><button id="msdlv" class="msbtn g">⬇ Without Formula</button><button id="msclear" class="msbtn z">Clear</button></div><div id="msrefinfo"></div><div id="msnote" class="msnote">Ready. Pehle Last Salary reference upload karo, phir Mam ki Sheet.</div><div id="msstats"></div><div id="msbody"></div></div>';var r=$('page-sync');if(r&&r.parentNode)r.parentNode.appendChild(p);else document.body.appendChild(p);if(!ok()){p.hidden=true;p.style.display='none'}}$('msref').onchange=function(){refFile(this.files[0])};$('msfile').onchange=function(){mamFile(this.files[0])};$('msdays').onchange=function(){S.days=C(+this.value||31,28,31);this.value=S.days;if(S.rows.length)auto()};$('msauto').onclick=auto;$('msdlf').onclick=function(){dl(true)};$('msdlv').onclick=function(){dl(false)};$('msfull').onclick=full;$('msclear').onclick=function(){S.rows=[];S.ref=null;$('msfile').value='';$('msref').value='';render();refNote();note('Cleared.',0)};$('msbody').oninput=$('msbody').onchange=function(ev){var e=ev.target;if(!e.dataset||e.dataset.i===undefined)return;var i=+e.dataset.i,r=S.rows[i],f=e.dataset.f;if(f==='cat'){r.cat=e.value;return}if(['rule','pfm','es'].includes(f)){r[f]=e.value;if(f==='rule'){suggest(r);render()}else upd(i);return}r[f]=f==='man'?N(e.value):+e.value||0;r.delta=null;upd(i)};render();refNote()}
function start(){if(window.XLSX)return inject();var s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';s.onload=inject;s.onerror=function(){alert('Excel library load nahi hui. Internet refresh karke retry karo.')};document.head.appendChild(s)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
