/* Arora ERP shared Google Apps Script auth bridge — FAST cross-browser users. */
(function(){'use strict';
var API='https://script.google.com/macros/s/AKfycby99_893hVtbWOQr67ikxIwiq81MWW8JAa2LuxTu67JBxjQ_iWb-YkqhBmW0RrHU512SQ/exec';
var USERS='ATPL_UserAccess_V1',SESS='ATPL_UserSession_V5',TOKEN='ATPL_RemoteToken_V1';
var remoteUsers=[];
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function readUsers(){try{var a=JSON.parse(localStorage.getItem(USERS)||'[]');return Array.isArray(a)?a:[]}catch(_){return[]}}
function currentUser(){try{var s=JSON.parse(sessionStorage.getItem(SESS)||'null');if(!s||!s.id)return null;return readUsers().find(function(u){return String(u.id).toLowerCase()===String(s.id).toLowerCase()})||null}catch(_){return null}}
function token(){return sessionStorage.getItem(TOKEN)||''}
function saveLocalUsers(a){localStorage.setItem(USERS,JSON.stringify(Array.isArray(a)?a:[]))}
function setLogin(u,t,all){saveLocalUsers(all&&all.length?all:[u]);sessionStorage.setItem(SESS,JSON.stringify({id:u.id}));sessionStorage.setItem(TOKEN,t)}
function clearLogin(){['ATPL_UserSession_V1','ATPL_UserSession_V2','ATPL_UserSession_V3','ATPL_UserSession_V4','ATPL_UserSession_V5',TOKEN].forEach(function(k){sessionStorage.removeItem(k)})}
function has(u,p){return !!u&&(u.admin===true||(Array.isArray(u.access)&&u.access.indexOf(p)>=0))}
function api(params){return new Promise(function(resolve,reject){var cb='__atpl_remote_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),done=false,t=setTimeout(function(){finish();reject(new Error('Login server se connection timeout hua.'))},10000);function finish(){if(done)return;done=true;clearTimeout(t);try{delete window[cb]}catch(_){window[cb]=undefined}if(s.parentNode)s.parentNode.removeChild(s)}window[cb]=function(data){finish();resolve(data||{})};params=params||{};params.callback=cb;var qs=Object.keys(params).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(params[k]==null?'':String(params[k]))}).join('&');s.onerror=function(){finish();reject(new Error('Login server connect nahi hua.'))};s.src=API+'?'+qs;document.head.appendChild(s)})}
function sha256(v){if(!window.crypto||!crypto.subtle||!window.TextEncoder)return Promise.reject(new Error('Secure login is browser me available nahi hai.'));return crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))).then(function(buf){return Array.prototype.map.call(new Uint8Array(buf),function(b){return('0'+b.toString(16)).slice(-2)}).join('')})}
function navFeatures(){return Array.prototype.map.call(document.querySelectorAll('.vitem[id^="vn-"]'),function(x){return{id:x.id.slice(3),name:(x.textContent||'').replace(/\s+/g,' ').trim(),el:x}}).filter(function(x){return x.id!=='useraccess'})}
function visible(el,ok){if(!el)return;if(ok){el.hidden=false;el.classList.remove('uaNoAccess','uaDeniedPage','uaEmptyGroup');el.style.removeProperty('display');el.removeAttribute('aria-hidden')}else{el.hidden=true;el.classList.add('uaNoAccess');el.style.setProperty('display','none','important');el.setAttribute('aria-hidden','true')}}
function applyAccess(){var u=currentUser(),fs=navFeatures(),ua=q('vn-useraccess');fs.forEach(function(f){visible(f.el,has(u,f.id))});visible(ua,!!(u&&u.admin===true));Array.prototype.forEach.call(document.querySelectorAll('[id^="page-"]'),function(pg){var id=pg.id.slice(5),ok=id==='useraccess'?!!(u&&u.admin===true):has(u,id);if(ok){pg.hidden=false;pg.classList.remove('uaDeniedPage','uaNoAccess');pg.style.removeProperty('display');pg.removeAttribute('aria-hidden')}else{pg.classList.remove('active');visible(pg,false)}});Array.prototype.forEach.call(document.querySelectorAll('.vnav-group'),function(g){var items=Array.prototype.slice.call(g.querySelectorAll('.vitem[id^="vn-"]')),ok=items.some(function(x){var id=x.id.slice(3);return id==='useraccess'?!!(u&&u.admin===true):has(u,id)});visible(g,ok)});var who=q('uaWho'),lo=q('uaLogoutBtn');if(who){who.style.display=u?'inline-flex':'none';who.textContent=u?'👤 '+(u.name||u.id):''}if(lo)lo.style.display=u?'inline-flex':'none'}
function firstAllowed(u){var x=navFeatures().find(function(f){return has(u,f.id)});return x?x.id:null}
function loginError(msg){var e=q('uaLoginErr');if(e)e.textContent=msg||''}
function setBusy(btn,busy,text){if(!btn)return;if(!btn.dataset.fastBase)btn.dataset.fastBase=btn.textContent;btn.disabled=!!busy;btn.style.opacity=busy?'.65':'1';btn.textContent=busy?(text||'Please wait...'):btn.dataset.fastBase}
async function getAllUsers(t){var r=await api({action:'listUsers',token:t});if(!r.ok)throw new Error(r.error||'Users load nahi hue.');return Array.isArray(r.users)?r.users:[]}
async function remoteLogin(){var id=q('uaLoginId'),pw=q('uaLoginPass'),btn=q('uaLoginBtn');if(!id||!pw||!btn)return;var uid=id.value.trim(),pass=pw.value;loginError('');if(!uid||!pass){loginError('User ID aur Password enter karo.');return}setBusy(btn,true,'VERIFYING...');try{var hash=await sha256(pass),r=await api({action:'login',user_id:uid,password_hash:hash});if(!r.ok||!r.user||!r.token)throw new Error(r.error||'Wrong User ID or Password.');setLogin(r.user,r.token,[r.user]);remoteUsers=[r.user];applyAccess();var p=firstAllowed(r.user);if(p&&typeof window.goPage==='function')window.goPage(p);var l=q('uaLogin');if(l)l.style.display='none';document.body.classList.remove('uaLocked');var landing=q('landingPage');if(landing){landing.style.display='flex';landing.style.opacity='1';landing.style.visibility='visible';landing.style.pointerEvents='auto'}}catch(ex){clearLogin();applyAccess();loginError(ex.message||'Login failed.')}finally{setBusy(btn,false)}}
function renderChecks(){var box=q('uaChecks');if(!box)return;box.innerHTML=navFeatures().map(function(f){var nm=(f.name||f.id).replace(/^\S+\s*/,'').trim()||f.id;return '<label class="uaCheck"><input type="checkbox" value="'+esc(f.id)+'"> '+esc(nm)+'</label>'}).join('')}
function renderRemoteUsers(){var box=q('uaList');if(!box)return;if(!remoteUsers.length){box.innerHTML='<div style="padding:14px;color:#64748b;font-size:11px">No users found.</div>';return}box.innerHTML=remoteUsers.map(function(u){return '<div class="uaUser"><div class="uaUserInfo"><b>'+esc(u.name||u.id)+'</b><span>ID: '+esc(u.id)+' · '+(u.admin===true?'ADMIN · All Features':esc((u.access||[]).join(', ')))+'</span></div><div class="uaActions">'+(u.admin===true?'':'<button class="uaMini uaEdit" data-r-edit="'+esc(u.id)+'">Edit</button><button class="uaMini uaDel" data-r-del="'+esc(u.id)+'">Delete</button>')+'</div></div>'}).join('')}
function clearForm(){['uaName','uaId','uaPass'].forEach(function(id){var x=q(id);if(x)x.value=''});Array.prototype.forEach.call(document.querySelectorAll('#uaChecks input'),function(c){c.checked=false});var t=q('uaFormTitle'),c=q('uaCancel'),id=q('uaId'),p=q('uaPass'),er=q('uaFormErr');if(t)t.textContent='Create User';if(c)c.style.display='none';if(id){id.disabled=false;id.style.opacity='1';delete id.dataset.remoteEdit}if(p)p.placeholder='Password';if(er)er.textContent=''}
function editRemoteUser(id){var u=remoteUsers.find(function(x){return String(x.id).toLowerCase()===String(id).toLowerCase()});if(!u||u.admin===true)return;var nm=q('uaName'),uid=q('uaId'),pw=q('uaPass');if(nm)nm.value=u.name||'';if(uid){uid.value=u.id;uid.disabled=true;uid.style.opacity='.7';uid.dataset.remoteEdit='1'}if(pw){pw.value='';pw.placeholder='Blank = keep old password'}Array.prototype.forEach.call(document.querySelectorAll('#uaChecks input'),function(c){c.checked=(u.access||[]).indexOf(c.value)>=0});if(q('uaFormTitle'))q('uaFormTitle').textContent='Edit User Access';if(q('uaCancel'))q('uaCancel').style.display='inline-block'}
async function openRemoteUsers(ev){if(ev){ev.preventDefault();ev.stopPropagation()}var u=currentUser();if(!u||u.admin!==true){alert('User Access sirf Admin ke liye hai.');return}var p=q('uaPage');if(p)p.style.display='block';renderChecks();clearForm();var box=q('uaList');if(box)box.innerHTML='<div style="padding:14px;color:#64748b;font-size:11px">Loading users...</div>';try{remoteUsers=await getAllUsers(token());saveLocalUsers(remoteUsers);renderRemoteUsers();applyAccess()}catch(ex){if(box)box.innerHTML='<div style="padding:14px;color:#dc2626;font-size:11px">'+esc(ex.message||'Users load nahi hue.')+'</div>'}}
function upsertLocalUser(u){var a=remoteUsers.slice(),i=a.findIndex(function(x){return String(x.id).toLowerCase()===String(u.id).toLowerCase()});if(i>=0)a[i]=u;else a.push(u);remoteUsers=a;saveLocalUsers(a);renderRemoteUsers()}
async function remoteSaveUser(){var u=currentUser(),t=token(),name=q('uaName'),id=q('uaId'),pw=q('uaPass'),err=q('uaFormErr'),btn=q('uaSave');if(!u||u.admin!==true||!t){if(err)err.textContent='Admin session required.';return}var nm=name?name.value.trim():'',uid=id?id.value.trim():'',pass=pw?pw.value:'',editing=!!(id&&id.dataset.remoteEdit),access=Array.prototype.filter.call(document.querySelectorAll('#uaChecks input'),function(c){return c.checked}).map(function(c){return c.value});if(err)err.textContent='';if(!nm||!uid){if(err)err.textContent='Name aur User ID required hai.';return}if(!editing&&!pass){if(err)err.textContent='Password required hai.';return}if(!access.length){if(err)err.textContent='Kam se kam 1 feature access select karo.';return}setBusy(btn,true,'SAVING...');try{var hash=pass?await sha256(pass):'',r=await api({action:'saveUser',token:t,user_id:uid,user_name:nm,password_hash:hash,is_admin:'false',feature_access:JSON.stringify(access)});if(!r.ok||!r.user)throw new Error(r.error||'User save failed.');upsertLocalUser(r.user);clearForm();alert('User saved. Same ID/password dusre Chrome ya computer me bhi chalega.')}catch(ex){if(err)err.textContent=ex.message||'User save failed.'}finally{setBusy(btn,false)}}
async function deleteRemoteUser(id){var u=currentUser(),t=token();if(!u||u.admin!==true||!t)return;var x=remoteUsers.find(function(v){return String(v.id).toLowerCase()===String(id).toLowerCase()});if(!x||x.admin===true)return;if(!confirm('Delete user '+x.id+'?'))return;try{var r=await api({action:'deleteUser',token:t,user_id:x.id});if(!r.ok)throw new Error(r.error||'Delete failed.');remoteUsers=remoteUsers.filter(function(v){return String(v.id).toLowerCase()!==String(x.id).toLowerCase()});saveLocalUsers(remoteUsers);renderRemoteUsers()}catch(ex){alert(ex.message||'Delete failed.')}}
function remoteLogout(){var t=token();clearLogin();saveLocalUsers([]);applyAccess();var l=q('uaLogin');if(l)l.style.display='flex';document.body.classList.add('uaLocked');var p=q('uaPage');if(p)p.style.display='none';if(q('uaLoginId'))q('uaLoginId').value='';if(q('uaLoginPass'))q('uaLoginPass').value='';loginError('');if(t)api({action:'logout',token:t}).catch(function(){})}
function install(){var lb=q('uaLoginBtn'),pw=q('uaLoginPass'),sv=q('uaSave'),lo=q('uaLogoutBtn'),nav=q('vn-useraccess'),cancel=q('uaCancel');if(!lb||!sv)return false;lb.onclick=remoteLogin;if(pw)pw.onkeydown=function(ev){if(ev.key==='Enter'){ev.preventDefault();remoteLogin()}};sv.onclick=remoteSaveUser;if(lo)lo.onclick=remoteLogout;if(nav)nav.onclick=openRemoteUsers;if(cancel)cancel.onclick=clearForm;if(!window.__ATPL_REMOTE_LISTENER){window.__ATPL_REMOTE_LISTENER=1;document.addEventListener('click',function(ev){var eb=ev.target&&ev.target.closest?ev.target.closest('#uaList [data-r-edit]'):null;if(eb){ev.preventDefault();ev.stopPropagation();editRemoteUser(eb.getAttribute('data-r-edit'));return}var db=ev.target&&ev.target.closest?ev.target.closest('#uaList [data-r-del]'):null;if(db){ev.preventDefault();ev.stopPropagation();deleteRemoteUser(db.getAttribute('data-r-del'))}},true)}var note=q('uaFormErr');if(note)note.setAttribute('data-shared-backend','google-apps-script-fast');return true}
function start(){if(window.__ATPL_SHARED_GOOGLE_AUTH_FAST)return;window.__ATPL_SHARED_GOOGLE_AUTH_FAST=1;if(!install())setTimeout(install,60)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();