/* Arora ERP shared Google Apps Script auth bridge — cross-browser users. */
(function(){'use strict';
var API='https://script.google.com/macros/s/AKfycby99_893hVtbWOQr67ikxIwiq81MWW8JAa2LuxTu67JBxjQ_iWb-YkqhBmW0RrHU512SQ/exec';
var USERS='ATPL_UserAccess_V1',SESS='ATPL_UserSession_V5',TOKEN='ATPL_RemoteToken_V1';
function q(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function currentUser(){try{var s=JSON.parse(sessionStorage.getItem(SESS)||'null'),a=JSON.parse(localStorage.getItem(USERS)||'[]');if(!s||!s.id||!Array.isArray(a))return null;return a.find(function(u){return String(u.id).toLowerCase()===String(s.id).toLowerCase()})||null}catch(_){return null}}
function token(){return sessionStorage.getItem(TOKEN)||''}
function saveLocalUsers(a){localStorage.setItem(USERS,JSON.stringify(Array.isArray(a)?a:[]))}
function setLogin(u,t,all){saveLocalUsers(all&&all.length?all:[u]);sessionStorage.setItem(SESS,JSON.stringify({id:u.id}));sessionStorage.setItem(TOKEN,t)}
function clearLogin(){sessionStorage.removeItem(SESS);sessionStorage.removeItem(TOKEN)}
function has(u,p){return !!u&&(u.admin===true||(Array.isArray(u.access)&&u.access.indexOf(p)>=0))}
function api(params){return new Promise(function(resolve,reject){var cb='__atpl_remote_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),done=false,t=setTimeout(function(){finish();reject(new Error('Login server se connection timeout hua.'))},15000);function finish(){if(done)return;done=true;clearTimeout(t);try{delete window[cb]}catch(_){window[cb]=undefined}if(s.parentNode)s.parentNode.removeChild(s)}window[cb]=function(data){finish();resolve(data||{})};params=params||{};params.callback=cb;var qs=Object.keys(params).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(params[k]==null?'':String(params[k]))}).join('&');s.onerror=function(){finish();reject(new Error('Login server connect nahi hua.'))};s.src=API+'?'+qs;document.head.appendChild(s)})}
function sha256(v){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v))).then(function(buf){return Array.prototype.map.call(new Uint8Array(buf),function(b){return('0'+b.toString(16)).slice(-2)}).join('')})}
function navFeatures(){return Array.prototype.map.call(document.querySelectorAll('.vitem[id^="vn-"]'),function(x){return{id:x.id.slice(3),el:x}}).filter(function(x){return x.id!=='useraccess'})}
function visible(el,ok){if(!el)return;if(ok){el.hidden=false;el.classList.remove('uaNoAccess','uaDeniedPage','uaEmptyGroup');el.style.removeProperty('display');el.removeAttribute('aria-hidden')}else{el.hidden=true;el.classList.add('uaNoAccess');el.style.setProperty('display','none','important');el.setAttribute('aria-hidden','true')}}
function applyAccess(){var u=currentUser(),fs=navFeatures(),ua=q('vn-useraccess');fs.forEach(function(f){visible(f.el,has(u,f.id))});visible(ua,!!(u&&u.admin===true));Array.prototype.forEach.call(document.querySelectorAll('[id^="page-"]'),function(pg){var id=pg.id.slice(5),ok=id==='useraccess'?!!(u&&u.admin===true):has(u,id);if(ok){pg.hidden=false;pg.classList.remove('uaDeniedPage','uaNoAccess');pg.style.removeProperty('display');pg.removeAttribute('aria-hidden')}else{pg.classList.remove('active');visible(pg,false)}});Array.prototype.forEach.call(document.querySelectorAll('.vnav-group'),function(g){var items=Array.prototype.slice.call(g.querySelectorAll('.vitem[id^="vn-"]')),ok=items.some(function(x){var id=x.id.slice(3);return id==='useraccess'?!!(u&&u.admin===true):has(u,id)});visible(g,ok)});var who=q('uaWho'),lo=q('uaLogoutBtn');if(who){who.style.display=u?'inline-flex':'none';who.textContent=u?'👤 '+(u.name||u.id):''}if(lo)lo.style.display=u?'inline-flex':'none'}
function firstAllowed(u){var x=navFeatures().find(function(f){return has(u,f.id)});return x?x.id:null}
function loginError(msg){var e=q('uaLoginErr');if(e)e.textContent=msg||''}
async function getAllUsers(t){var r=await api({action:'listUsers',token:t});if(!r.ok)throw new Error(r.error||'Users load nahi hue.');return Array.isArray(r.users)?r.users:[]}
async function remoteLogin(){var id=q('uaLoginId'),pw=q('uaLoginPass'),btn=q('uaLoginBtn');if(!id||!pw||!btn)return;var uid=id.value.trim(),pass=pw.value;loginError('');if(!uid||!pass){loginError('User ID aur Password enter karo.');return}btn.disabled=true;var old=btn.textContent;btn.textContent='VERIFYING...';try{var hash=await sha256(pass),r=await api({action:'login',user_id:uid,password_hash:hash});if(!r.ok||!r.user||!r.token)throw new Error(r.error||'Wrong User ID or Password.');var all=r.user.admin===true?await getAllUsers(r.token):[r.user];setLogin(r.user,r.token,all);applyAccess();var p=firstAllowed(r.user);if(p&&typeof window.goPage==='function')window.goPage(p);var l=q('uaLogin');if(l)l.style.display='none';document.body.classList.remove('uaLocked');var landing=q('landingPage');if(landing){landing.style.display='flex';landing.style.opacity='1';landing.style.visibility='visible';landing.style.pointerEvents='auto'}}catch(ex){clearLogin();applyAccess();loginError(ex.message||'Login failed.')}finally{btn.disabled=false;btn.textContent=old}}
async function refreshAdminUsers(){var t=token();if(!t)return[];var a=await getAllUsers(t);saveLocalUsers(a);return a}
function reopenUserPage(){var p=q('uaPage');if(p)p.style.display='none';var n=q('vn-useraccess');if(n)n.click()}
async function remoteSaveUser(){var u=currentUser(),t=token(),name=q('uaName'),id=q('uaId'),pw=q('uaPass'),err=q('uaFormErr'),btn=q('uaSave');if(!u||u.admin!==true||!t){if(err)err.textContent='Admin session required.';return}var nm=name?name.value.trim():'',uid=id?id.value.trim():'',pass=pw?pw.value:'',editing=!!(id&&id.disabled),access=Array.prototype.filter.call(document.querySelectorAll('#uaChecks input'),function(c){return c.checked}).map(function(c){return c.value});if(err)err.textContent='';if(!nm||!uid){if(err)err.textContent='Name aur User ID required hai.';return}if(!editing&&!pass){if(err)err.textContent='Password required hai.';return}if(!access.length){if(err)err.textContent='Kam se kam 1 feature access select karo.';return}if(btn){btn.disabled=true;btn.textContent='Saving...'}try{var hash=pass?await sha256(pass):'',r=await api({action:'saveUser',token:t,user_id:uid,user_name:nm,password_hash:hash,is_admin:'false',feature_access:JSON.stringify(access)});if(!r.ok)throw new Error(r.error||'User save failed.');await refreshAdminUsers();reopenUserPage();alert('User saved. Ab same ID/password dusre Chrome ya computer me bhi chalega.')}catch(ex){if(err)err.textContent=ex.message||'User save failed.'}finally{if(btn){btn.disabled=false;btn.textContent='💾 Save User'}}}
async function remoteDeleteByIndex(i){var u=currentUser(),t=token();if(!u||u.admin!==true||!t)return;var a=[];try{a=JSON.parse(localStorage.getItem(USERS)||'[]')}catch(_){a=[]}var x=a[i];if(!x||x.admin===true)return;if(!confirm('Delete user '+x.id+'?'))return;try{var r=await api({action:'deleteUser',token:t,user_id:x.id});if(!r.ok)throw new Error(r.error||'Delete failed.');await refreshAdminUsers();reopenUserPage()}catch(ex){alert(ex.message||'Delete failed.')}}
function remoteLogout(){var t=token();clearLogin();saveLocalUsers([]);applyAccess();var l=q('uaLogin');if(l)l.style.display='flex';document.body.classList.add('uaLocked');var p=q('uaPage');if(p)p.style.display='none';if(q('uaLoginId'))q('uaLoginId').value='';if(q('uaLoginPass'))q('uaLoginPass').value='';loginError('');if(t)api({action:'logout',token:t}).catch(function(){})}
function install(){var lb=q('uaLoginBtn'),pw=q('uaLoginPass'),sv=q('uaSave'),lo=q('uaLogoutBtn');if(!lb||!sv)return false;lb.onclick=remoteLogin;if(pw)pw.onkeydown=function(ev){if(ev.key==='Enter'){ev.preventDefault();remoteLogin()}};sv.onclick=remoteSaveUser;if(lo)lo.onclick=remoteLogout;document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('#uaList [data-del]'):null;if(!b)return;ev.preventDefault();ev.stopPropagation();if(ev.stopImmediatePropagation)ev.stopImmediatePropagation();remoteDeleteByIndex(+b.dataset.del)},true);var note=q('uaFormErr');if(note)note.setAttribute('data-shared-backend','google-apps-script');return true}
function start(){if(window.__ATPL_SHARED_GOOGLE_AUTH)return;window.__ATPL_SHARED_GOOGLE_AUTH=1;if(!install()){setTimeout(function(){install()},100)}api({action:'ping'}).catch(function(){})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
